global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'techshop'
    environment: 'production'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "/etc/prometheus/alerts/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:8001']
        labels:
          service: 'product'
          tier: 'backend'

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8002']
        labels:
          service: 'order'
          tier: 'backend'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8003']
        labels:
          service: 'payment'
          tier: 'backend'
          critical: 'true'

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8004']
        labels:
          service: 'user'
          tier: 'backend'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'database'
          tier: 'data'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'cache'
          tier: 'data'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']